CREATE SCHEMA IF NOT EXISTS app;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS app.user_account (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id   UUID NOT NULL DEFAULT gen_random_uuid(),

    first_name    VARCHAR(80),
    last_name     VARCHAR(80),

    email         VARCHAR(320) NOT NULL,

    birth_date    DATE,

    phone_number  VARCHAR(32),

    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    version       INTEGER NOT NULL DEFAULT 0,

    password_hash VARCHAR(255) NOT NULL,

    display_name  VARCHAR(120),

    status        VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',

    global_role   VARCHAR(40) NOT NULL DEFAULT 'USER',

    avatar_url    VARCHAR(2048),

    CONSTRAINT uq_user_account_external_id UNIQUE (external_id),
    CONSTRAINT uq_user_account_email       UNIQUE (email),
    CONSTRAINT uq_user_account_phone       UNIQUE (phone_number)
);

-- indeksy zgodne z @Table(indexes=...)
CREATE INDEX IF NOT EXISTS ix_user_account_external_id ON app.user_account(external_id);
CREATE INDEX IF NOT EXISTS ix_user_account_email       ON app.user_account(email);

-- (opcjonalnie) jeśli filtrujesz po statusie
CREATE INDEX IF NOT EXISTS ix_user_account_status      ON app.user_account(status);

-- (opcjonalnie) jeśli filtrujesz po roli
CREATE INDEX IF NOT EXISTS ix_user_account_global_role ON app.user_account(global_role);
